#Docker compose


version: '3.7'

services:

  wordpress:
    image: cayman7593/wordpress-vernice 
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      #WORDPRESS_DB_PASSWORD: /run/secrets/wordpress_db_password
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: exampledb

    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress-vernice
    secrets:
      - db_password

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      #MYSQL_PASSWORD: /run/secrets/my_sql_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordpress-vernice
    secrets:
      - db_password

volumes:
  wordpress:
  db:

secrets:
   db_password:
     file: ./db_password.txt
 
networks:
  wordpress-vernice:
  


  
   
