#Docker compose


version: '3.9'

services:

  wordpress:
    image: cayman7593/wordpress-vernice 
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: run/secrets/wordpress_db_password
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: run/secrets/my_sql_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:

secrets:
  wordpress_db_password:  
    file: wordpress_db_password.txt
  my_sql_password:
    file: my_sql_password.txt
   
